### ISSUE TITLE
conficted with the TouchUI plugin

### ISSUE THREAD

**Issue by everdom** [SanderRonde/Octoprint-Draggable-Files#7] opened 2021-05-28 06:55 UTC
I installed the TouchUI plguin, so  I  can use octoprint on my phone, but I can't drag files, and I can't select the gcode file to print!

**Comment by SanderRonde** [comment] 2021-05-31 01:44
The first part of not being able to drag files on mobile is correct. The plugin is disabled on mobile since it doesn't appear to work there (and also makes selecting gcode files very hard). I can't seem to reproduce the second part (not being able to select gcode files). Could something else be causing the issue? Regarding what I just said in the first part (the plugin being basically disabled on mobile), it would surprise me if it's causing any issues.

**Comment by everdom** [comment] 2021-06-15 03:35
OK, as you said, I really have installed a lot of plugins， I don't know which other plug-ins will cause this problem.  and just my octoprint  also have some other problems， so I simply reinstall my octoprint and only install TouchUI and Octoprint-Draggable-Files, there is no more problems I said before.

**Comment by SanderRonde** [comment] 2021-06-15 03:43
Great! It may also be fixed because of the recent updates to the plugin. Regardless, it's good to hear the problem has been fixed. I'll close the issue then.

**Closed as completed by SanderRonde** 2021-06-15 03:43 UTC
