### ISSUE TITLE
Drag&Drop don't work - incompatible with Slicer Thumbnails plugin

### ISSUE THREAD

**Issue by DangeMask** [SanderRonde/Octoprint-Draggable-Files#6] opened 2021-05-28 06:23 UTC
May be similar to https://github.com/SanderRonde/Octoprint-Draggable-Files/issues/3 but in my case, I can drag, but drop does nothing
![iKYf6joktP](https://user-images.githubusercontent.com/47944010/119939019-8524af80-bf8d-11eb-88ee-648d25081543.gif)
Using Firefox 88.0.1
OctoPrint 1.6.1
Python 3.7.3
OctoPi 0.18.0
The only plugin IMHO corresponding with this may be UI Customizer: 0.1.5.9 

I'll try to disable UI customizer when my print finishes to test the compatibility. If you need any details or tests, let me know, I'll be happy to help.

**Comment by SanderRonde** [comment] 2021-05-31 01:37
I seem to be unable to reproduce the issue, even with UI customizer installed. Could you list the other plugins you're using? And could you try to open the dev tools (press F12) and see if anything pops up there when you drop the file?

**Comment by DangeMask** [comment] 2021-05-31 07:30
Got it! I searched my 3rd party plugins and realised I also have Slicer Thumbnails installed. When I disabled that plugin, drag&drop started working again. Updating the issue name accordingly.
https://github.com/jneilliii/OctoPrint-PrusaSlicerThumbnails
I don't use the feature to show thumbnails in list of files, but still the plugin is useful for me to check the selected file before printing.

In developer tools, I have found nothing. The issue is, the folders are not highlighted when I hoved over them with dragged file, so no event is fired on "drop".
And resizinf the file list works OK.

**Comment by SanderRonde** [comment] 2021-06-08 20:13
Sorry for the late response, this was a tricky one to nail down. The issue should be fixed in 9324f82d9c5c98ab447cbdf853c6f119edcfa5c0. Additionally, I've sort of revamped the dragging mechanism so that should go a long way towards fixing future bugs like this as well.

**Closed as completed by SanderRonde** 2021-06-08 20:13 UTC

**Comment by DangeMask** [comment] 2021-06-10 10:22
Thank you, now it works great.
Just one issue: It looks like you renamed the repository in github and Octoprint is not able to find the new release. I solved it by uninstalling and reinstalling the plugin.
